// Copyright (C) 2026 Toit contributors.
// Use of this source code is governed by a BSD0-style license that can be
// found in the LICENSE file.

import encoding.yaml
import fs
import host.directory
import host.file
import json-schema
import json-schema.gen as schema-gen
import json-schema.schema as json-schema
import json-schema.action as schema-action
import system
import toit-gen
import toit-gen.namer

import .openapi

// Toit packages referenced from generated code. Each $toit-gen.Package
// carries its identifying URL plus the prefix used in the generated
// `import`s and `package.yaml`.
HTTP-PACKAGE_/toit-gen.Package ::= toit-gen.Package
    --prefix="http"
    --id="github.com/toitlang/pkg-http"
NET-PACKAGE_/toit-gen.Package ::= toit-gen.Package.sdk --prefix="net"
RUNTIME-PACKAGE_/toit-gen.Package ::= toit-gen.Package
    --prefix="openapi-runtime"
    --id="github.com/toitware/toit-openapi-runtime"
ENCODING-PACKAGE_/toit-gen.Package ::= toit-gen.Package.sdk --prefix="encoding"

/**
Resolves OpenAPI/JSON-Schema types to $toit-gen.Class instances usable as
  $toit-gen.RefTarget in generated type annotations.

Primitives short-circuit through $simple-type-of_. `$ref` schemas that
  point at a target registered through $models return the generated
  model class (so a body typed as `$ref: '#/components/schemas/Pet'`
  becomes `body/Pet`, with `Pet` defined in `models.toit`).

Schemas that fall through both branches keep today's stub behavior: an
  imported $toit-gen.Class with the hint or fragment-derived name. That
  path covers inline schemas not registered through $models and is the
  thing Phase 4 deliberately leaves alone.
*/
class TypeResolver:
  any-class/toit-gen.Class ::= toit-gen.Class.core "any"
  list-class/toit-gen.Class ::= toit-gen.Class.core "List"
  map-class/toit-gen.Class ::= toit-gen.Class.core "Map"
  byte-array-class/toit-gen.Class ::= toit-gen.Class.core "ByteArray"
  bool-class/toit-gen.Class ::= toit-gen.Class.core "bool"
  int-class/toit-gen.Class ::= toit-gen.Class.core "int"
  num-class/toit-gen.Class ::= toit-gen.Class.core "num"
  string-class/toit-gen.Class ::= toit-gen.Class.core "string"

  /// One $toit-gen.Ref per unique json-schema $Schema, keyed by identity.
  resolved/Map ::= {:}

  /// $schema-gen.Models populated by $ApiGenerator.gen, or null when the
  /// document has no `components.schemas`.
  models/schema-gen.Models? := null

  /// Import emitted into `api.toit` to reach classes in `models.toit`.
  /// Set by $ApiGenerator.gen alongside $models.
  models-import/toit-gen.Import? := null

  /**
  Returns the $toit-gen.Ref to use as the type for $open-api-schema.

  $hint is used as a fallback name when the schema has no nameable URL.
  Refs to classes generated by toit-json-schema are returned as
  $toit-gen.ImportedRef so that `api.toit` correctly imports `models.toit`.
  */
  resolve open-api-schema/Schema? --hint/string -> toit-gen.Ref:
    if not open-api-schema: return toit-gen.Ref any-class
    js/json-schema.Schema := open-api-schema.schema.schema

    if resolved.contains js: return resolved[js]

    simple := simple-type-of_ js
    if simple:
      ref := toit-gen.Ref simple
      resolved[js] = ref
      return ref

    if models and js.is-reference-only:
      target-uri := js.reference-target-uri
      generated := models.lookup-by-uri target-uri
      if generated:
        ref := models-import
            ? (models-import.refer generated)
            : toit-gen.Ref generated
        resolved[js] = ref
        return ref

    name := hint
    if js.is-reference-only:
      target-uri := js.reference-target-uri
      json-schema-name := (target-uri.fragment.split "%2F").last
      name = json-schema-name

    clazz := toit-gen.Class.imported (namer.toit-class-name name)
    ref := toit-gen.Ref clazz
    resolved[js] = ref
    return ref

  simple-type-of_ js/json-schema.Schema -> toit-gen.Class?:
    js.actions.do: | action/schema-action.Action |
      if action is schema-action.Type:
        type-action := action as schema-action.Type
        accepted := type-action.types
        if accepted.size != 1: return null
        type := accepted.first
        if type == "integer": return int-class
        if type == "number": return num-class
        if type == "string": return string-class
        if type == "boolean": return bool-class
        if type == "null": return any-class
        if type == "array": return list-class
        if type == "object": return map-class
        return null
    return null

/**
Builds a $toit-gen.Program for a given $OpenApi document.
*/
class ApiGenerator:
  type-resolver/TypeResolver

  // Imports — set up at the start of $gen and used as $RefTarget seeds for
  // every imported symbol via $toit-gen.Import.refer.
  http_/toit-gen.Import? := null
  net_/toit-gen.Import? := null
  runtime_/toit-gen.Import? := null
  /// $api-library_ is captured here so $ensure-json-import_ can lazily add
  ///   `import encoding.json` only when an operation actually needs it.
  api-library_/toit-gen.Library? := null
  json_/toit-gen.Import? := null

  // Stub classes for imported types. They exist purely as $RefTarget; their
  // bodies and members are not generated.
  http-response_/toit-gen.Class ::= toit-gen.Class.imported "Response"
  http-headers_/toit-gen.Class ::= toit-gen.Class.imported "Headers"
  net-client_/toit-gen.Class ::= toit-gen.Class.imported "Client"
  api-client_/toit-gen.Class ::= toit-gen.Class.imported "ApiClient"
  authentication_/toit-gen.Class ::= toit-gen.Class.imported "Authentication"

  // Free-standing imported names treated as $RefTarget via $VarDefinition.
  encode-query-param_/toit-gen.VarDefinition ::= imported-name_ "encode-query-param"
  encode-header-param_/toit-gen.VarDefinition ::= imported-name_ "encode-header-param"
  json-encode_/toit-gen.VarDefinition ::= imported-name_ "encode"
  json-decode_/toit-gen.VarDefinition ::= imported-name_ "decode"

  constructor --.type-resolver:

  /**
  Lazily adds `import encoding.json` to $api-library_ on first use, so a
    spec with no JSON request/response bodies doesn't carry the import.
  */
  ensure-json-import_ -> toit-gen.Import:
    if json_: return json_
    json_ = api-library_.add-import ENCODING-PACKAGE_ --module="json"
    return json_

  /**
  Populates the model library with classes generated from
    `components.schemas.*` and stores the resulting $schema-gen.Models on
    $type-resolver.

  No-op when the document has no `components.schemas`. The model library
    is created only when there is at least one schema to put in it, so a
    schema-less spec generates a single `api.toit` exactly as before.
  */
  populate-models_ openapi/OpenApi
      --program/toit-gen.Program
      --api-library/toit-gen.Library -> none:
    if not openapi.components: return
    schemas := openapi.components.schemas
    if not schemas or schemas.is-empty: return

    json-schemas := []
    schemas.do: | _ schema/Schema |
      json-schemas.add schema.schema

    models-lib := toit-gen.Library "src/models.toit"
    program.libraries.add models-lib
    type-resolver.models = schema-gen.populate program json-schemas
        --library-for-uri=:: models-lib
    type-resolver.models-import = api-library.add-relative-import "models"

  /**
  Builds a $toit-gen.VarDefinition that can be used as a RefTarget for an
    imported name (a function or top-level value, not a class).
  */
  static imported-name_ name/string -> toit-gen.VarDefinition:
    vd := toit-gen.VarDefinition.local name --initial=(toit-gen.Literal null)
    vd.name = name
    return vd

  /**
  Generates a $toit-gen.Program for the given $openapi document.

  The returned program contains a single library at "src/api.toit" with a
    main `Api` class plus one per-tag API class.
  */
  gen openapi/OpenApi -> toit-gen.Program:
    program := toit-gen.Program
    library := toit-gen.Library "src/api.toit"
    program.libraries.add library
    api-library_ = library

    // import http
    // import net
    // import openapi-runtime
    http_ = library.add-import HTTP-PACKAGE_
    net_ = library.add-import NET-PACKAGE_
    runtime_ = library.add-import RUNTIME-PACKAGE_

    // Generate model classes for `components.schemas.*` into a sibling
    //   `src/models.toit` library. Cross-library refs from `api.toit`
    //   (e.g. a request body typed as `Pet`) become real types after this.
    populate-models_ openapi --program=program --api-library=library

    // class Api:
    //   api-client_/openapi-runtime.ApiClient? := null
    api-class := library.add-class "Api"
    api-class.name = "Api"

    api-client-field := api-class.add-field "api-client"
        --type=(runtime_.refer api-client_)
        --is-nullable=true
        --is-final=false
        --is-private=true

    add-api-constructors_ api-class api-client-field
    add-close-method_ api-class api-client-field

    // Build per-tag classes plus their getters/fields on Api.
    tag-descriptions := {:}
    (openapi.tags or []).do: | tag/Tag |
      tag-descriptions[tag.name] = tag.description

    tag-classes := {:}     // tag-name → toit-gen.Class
    tag-operations := {:}  // tag-name → list of [path, method, Operation]

    openapi.paths.paths.do: | path/string path-item/PathItem |
      PathItem.OPERATION-KINDS.do: | method/string |
        operation := path-item.operation method
        if not operation: continue.do
        tag-name := (operation.tags and not operation.tags.is-empty)
            ? operation.tags.first
            : ""
        ops := tag-operations.get tag-name --init=: []
        ops.add [path, method, operation]

    tag-operations.do: | tag-name/string _ |
      preferred := tag-name == ""
          ? "DefaultApi"
          : "$(namer.toit-class-name tag-name)Api"
      tag-classes[tag-name] = library.add-class preferred

    tag-classes.do: | _ tag-class/toit-gen.Class |
      add-tag-getter_ api-class tag-class api-client-field

    tag-classes.do: | tag-name/string tag-class/toit-gen.Class |
      description := tag-descriptions.get tag-name
      if description: tag-class.toitdoc = [description]
      build-tag-class_ tag-class --operations=tag-operations[tag-name]

    return program

  /**
  Adds the two `Api` constructors:
    - `constructor --api-client/openapi-runtime.ApiClient`
    - `constructor network/net.Client`
  */
  add-api-constructors_ api-class/toit-gen.Class field/toit-gen.VarDefinition -> none:
    // constructor --api-client/openapi-runtime.ApiClient:
    //   api-client_ = api-client
    api-client-param := toit-gen.VarDefinition.parameter "api-client"
        --type=(runtime_.refer api-client_)
        --is-named=true
    api-client-param.name = "api-client"
    body1 := toit-gen.Sequence
    body1.assign field (toit-gen.Ref api-client-param)
    api-class.add-constructor --parameters=[api-client-param] body1

    // constructor network/net.Client:
    //   api-client_ = openapi-runtime.ApiClient network --base-path=""
    network-param := toit-gen.VarDefinition.parameter "network"
        --type=(net_.refer net-client_)
    network-param.name = "network"
    body2 := toit-gen.Sequence
    body2.assign field
        toit-gen.Call (runtime_.refer api-client_)
            --arguments=[
              toit-gen.Ref network-param,
              toit-gen.Named.external "base-path" (toit-gen.Literal ""),
            ]
    api-class.add-constructor --parameters=[network-param] body2

  /**
  Adds the `close` method:

    close -> none:
      if not api-client_: return
      api-client_.close
      api-client_ = null
  */
  add-close-method_ api-class/toit-gen.Class field/toit-gen.VarDefinition -> none:
    body := toit-gen.Sequence
    // if not api-client_: return
    early-return := toit-gen.Sequence
    early-return.ret
    body.iff
        (toit-gen.Unary "not" (toit-gen.Ref field))
        early-return
    // api-client_.close
    body.invoke (toit-gen.Ref field) "close"
    // api-client_ = null
    body.assign field (toit-gen.Literal null)
    api-class.add-method "close" --parameters=[] body

  /**
  Adds the lazy-init field + getter on `Api` for one per-tag API class:

    pets-api_/PetsApi? := null
    pets-api -> PetsApi:
      if not pets-api_: pets-api_ = PetsApi api-client_
      return pets-api_
  */
  add-tag-getter_ api-class/toit-gen.Class
      tag-class/toit-gen.Class
      api-client-field/toit-gen.VarDefinition -> none:
    name := tag-class.preferred-name  // E.g. "PetsApi".
    // pets-api_/PetsApi? := null
    field := api-class.add-field name
        --type=(toit-gen.Ref tag-class)
        --is-nullable=true
        --is-final=false
        --is-private=true
        --initial=(toit-gen.Literal null)

    // pets-api -> PetsApi:
    //   if not pets-api_: pets-api_ = PetsApi api-client_
    //   return pets-api_
    body := toit-gen.Sequence
    init := toit-gen.Sequence
    init.assign field
        (toit-gen.Call (toit-gen.Ref tag-class) --arguments=[toit-gen.Ref api-client-field])
    body.iff (toit-gen.Unary "not" (toit-gen.Ref field)) init
    body.ret (toit-gen.Ref field)
    api-class.add-method name --parameters=[] --return-type=(toit-gen.Ref tag-class) body

  /**
  Builds a per-tag class with its constructor and operations.
  */
  build-tag-class_ tag-class/toit-gen.Class --operations/List -> none:
    // authentication/openapi-runtime.Authentication? := null
    auth-field := tag-class.add-field "authentication"
        --type=(runtime_.refer authentication_)
        --is-nullable=true
        --is-final=false
        --initial=(toit-gen.Literal null)
    // api-client_/openapi-runtime.ApiClient
    api-client-field := tag-class.add-field "api-client"
        --type=(runtime_.refer api-client_)
        --is-final=false
        --is-private=true

    // constructor client/openapi-runtime.ApiClient
    //     --auth/openapi-runtime.Authentication?=null:
    //   api-client_ = client
    //   authentication = auth
    client-param := toit-gen.VarDefinition.parameter "client"
        --type=(runtime_.refer api-client_)
    auth-param := toit-gen.VarDefinition.parameter "auth"
        --type=(runtime_.refer authentication_)
        --is-named=true
        --is-nullable=true
        --initial=(toit-gen.Literal null)
    body := toit-gen.Sequence
    body.assign api-client-field (toit-gen.Ref client-param)
    body.assign auth-field (toit-gen.Ref auth-param)
    tag-class.add-constructor --parameters=[client-param, auth-param] body

    operations.do: | entry/List |
      build-operation_ tag-class
          --path=entry[0]
          --method=entry[1]
          --operation=entry[2]
          --api-client-field=api-client-field

  /**
  Builds the two methods (raw + regular variant) for one $operation.
  */
  build-operation_ tag-class/toit-gen.Class
      --path/string
      --method/string
      --operation/Operation
      --api-client-field/toit-gen.VarDefinition -> none:
    op-name := operation.operation-id
        ? namer.toit-member-name operation.operation-id
        : namer.toit-member-name "$path-$method"
    parameters := operation.parameters or []
    has-cookie := parameters.any: | p/Parameter | p.in == Parameter.COOKIE

    request-body-type/toit-gen.Ref? := null
    request-body-description/string? := null
    body-needs-json-encode := false  // True when body is a generated model.
    if operation.request-body:
      resolved := operation.request-body.resolved-request-body
      request-body-description = resolved.description
      content := resolved.content
      if content.contains "application/json":
        request-body-type = type-resolver.resolve content["application/json"].schema
            --hint="$path-$(method)-request-body"
        body-needs-json-encode = is-model-class_ request-body-type
      else:
        request-body-type = toit-gen.Ref type-resolver.byte-array-class

    response-model := response-model_ operation --hint="$path-$(method)-response"

    // VarDefinitions for the formal parameters: built once per variant since
    // an AST node can't appear under two Function nodes.
    fresh-params := :
      parameters.map: | param/Parameter | [param, param-vd_ param --path=path --method=method]

    // --- Raw variant ---
    // op-name --raw [--p1=...] [--p2=...] [body/Body] -> http.Response:
    //   <build-operation-body_>
    raw-flag := raw-flag-vd_
    raw-params := fresh-params.call
    raw-body-arg := request-body-type ? body-vd_ request-body-type : null
    raw-fn-params := [raw-flag]
    raw-params.do: | pair/List | raw-fn-params.add pair[1]
    if raw-body-arg: raw-fn-params.add raw-body-arg

    raw-fn := tag-class.add-method op-name
        --parameters=raw-fn-params
        --return-type=(http_.refer http-response_)
        (build-operation-body_
            --path=path
            --method=method
            --params=raw-params
            --request-body-arg=raw-body-arg
            --body-needs-json-encode=body-needs-json-encode
            --has-cookie=has-cookie
            --api-client-field=api-client-field)
    if operation.deprecated: raw-fn.toitdoc = ["Deprecated."]

    // --- Regular variant ---
    // op-name [--p1=...] [--p2=...] [body/Body] [-> ResponseModel]:
    //   <call --raw + optional deserialize-and-return>
    regular-params := fresh-params.call
    regular-body-arg := request-body-type ? body-vd_ request-body-type : null
    regular-fn-params := []
    regular-params.do: | pair/List | regular-fn-params.add pair[1]
    if regular-body-arg: regular-fn-params.add regular-body-arg

    raw-call-args := [toit-gen.Named raw-flag (toit-gen.Literal true)]
    regular-params.do: | pair/List |
      raw-vd := find-matching_ raw-params (pair[0] as Parameter)
      raw-call-args.add (toit-gen.Named raw-vd (toit-gen.Ref pair[1]))
    if regular-body-arg: raw-call-args.add (toit-gen.Ref regular-body-arg)

    regular-body := toit-gen.Sequence
    regular-return-type/toit-gen.Ref? := null
    if response-model:
      // response := op --raw ...
      // return Model.from-json (json.decode response.body.read-all)
      raw-call := toit-gen.Call (toit-gen.Ref raw-fn) --arguments=raw-call-args
      response-vd := regular-body.define "response" raw-call
      json-imp := ensure-json-import_
      body-bytes := toit-gen.Call
          (toit-gen.Call (toit-gen.Ref response-vd) "body")
          "read-all"
      decoded := toit-gen.Call (json-imp.refer json-decode_) --arguments=[body-bytes]
      regular-body.ret
          (toit-gen.Call response-model "from-json" --arguments=[decoded])
      regular-return-type = response-model
    else:
      regular-body.call (toit-gen.Ref raw-fn) --arguments=raw-call-args
      regular-body.ret (toit-gen.Literal null)

    regular-fn := tag-class.add-method op-name
        --parameters=regular-fn-params
        --return-type=regular-return-type
        regular-body
    regular-fn.toitdoc = build-toitdoc_ operation
        --params=regular-params
        --request-body-arg=regular-body-arg
        --request-body-description=request-body-description

  /**
  A formal $toit-gen.VarDefinition for an OpenAPI $Parameter.

  Required → named, non-nullable.  Optional → named, nullable, default `null`.
  */
  param-vd_ param/Parameter --path/string --method/string -> toit-gen.VarDefinition:
    type := type-resolver.resolve param.schema --hint="$path-$method-$param.name"
    if param.required == true:
      return toit-gen.VarDefinition.parameter param.name
          --type=type
          --is-named=true
    return toit-gen.VarDefinition.parameter param.name
        --type=type
        --is-named=true
        --is-nullable=true
        --initial=(toit-gen.Literal null)

  raw-flag-vd_ -> toit-gen.VarDefinition:
    raw := toit-gen.VarDefinition.parameter "raw"
        --type=(toit-gen.Ref (toit-gen.Class.core "True"))
        --is-named=true
    raw.name = "raw"
    return raw

  body-vd_ type/toit-gen.Ref -> toit-gen.VarDefinition:
    return toit-gen.VarDefinition.parameter "body" --type=type

  static find-matching_ pairs/List target-param/Parameter -> toit-gen.VarDefinition:
    pairs.do: | pair/List |
      if (pair[0] as Parameter) == target-param: return pair[1]
    throw "raw parameter not found"

  /**
  Whether $ref points at a class in the generated `models.toit` library.

  Used to decide whether to JSON-encode bodies and JSON-decode responses.
    Stub `Class.imported` types created when no models library is wired
    up are not ImportedRef and so always return false.
  */
  is-model-class_ ref/toit-gen.Ref -> bool:
    if not type-resolver.models-import: return false
    return ref is toit-gen.ImportedRef
        and (ref as toit-gen.ImportedRef).imp == type-resolver.models-import

  /**
  Returns the Ref to the response model class for $operation, or null if
    there is no `application/json` response with a model schema.

  Picks the first 2xx response that has an `application/json` content
    entry; falls back to `default`. The schema must resolve to a class
    generated through the models library — primitive responses and
    inline `type: object` (which resolves to `Map`) are skipped.
  */
  response-model_ operation/Operation --hint/string -> toit-gen.Ref?:
    responses := operation.responses
    if not responses: return null
    candidates := []
    responses.responses.do: | code/string r/ResponseOrReference |
      if code.size > 0 and code[0] == '2': candidates.add r
    if responses.default: candidates.add responses.default
    candidates.do: | r/ResponseOrReference |
      response := r.resolved-response
      content := response.content
      if not content: continue.do
      if not content.contains "application/json": continue.do
      schema := content["application/json"].schema
      if not schema: continue.do
      ref := type-resolver.resolve schema --hint=hint
      if is-model-class_ ref: return ref
    return null

  /**
  Builds the body of the raw variant: locals for `path`, `headers`,
    `query-params`, `cookie-params`; per-parameter handling; `headers.set
    "Content-Type"` for JSON bodies; and the final `api-client_.invoke-api`.
  */
  build-operation-body_
      --path/string
      --method/string
      --params/List
      --request-body-arg/toit-gen.VarDefinition?
      --body-needs-json-encode/bool=false
      --has-cookie/bool
      --api-client-field/toit-gen.VarDefinition -> toit-gen.Sequence:
    body := toit-gen.Sequence
    // path := "<path>"
    // headers := http.Headers
    // query-params := []
    // cookie-params := []
    path-var := body.define "path" (toit-gen.Literal path)
    headers-var := body.define "headers" (toit-gen.Call (http_.refer http-headers_))
    query-var := body.define "query-params" (toit-gen.Literal [])
    cookie-var := body.define "cookie-params" (toit-gen.Literal [])

    // For each parameter, emit the appropriate path/query/header/cookie
    // handling — wrapped in `if param != null:` for optional parameters.
    params.do: | pair/List |
      param/Parameter := pair[0]
      vd/toit-gen.VarDefinition := pair[1]
      branch := toit-gen.Sequence
      append-param-handling_ branch
          --param=param
          --vd=vd
          --path-var=path-var
          --headers-var=headers-var
          --query-var=query-var
          --cookie-var=cookie-var
      if param.required == true:
        branch.statements.do: | stmt/toit-gen.Statement | body.add stmt
      else:
        body.iff
            (toit-gen.Binary (toit-gen.Ref vd) "!=" (toit-gen.Literal null))
            branch

    if has-cookie:
      // headers.set "Cookie" (cookie-params.join "; ")
      join-call := toit-gen.Call (toit-gen.Ref cookie-var) "join"
          --arguments=[toit-gen.Literal "; "]
      body.invoke (toit-gen.Ref headers-var) "set"
          --arguments=[toit-gen.Literal "Cookie", join-call]

    if request-body-arg:
      // headers.set "Content-Type" "application/json"
      body.invoke (toit-gen.Ref headers-var) "set"
          --arguments=[
            toit-gen.Literal "Content-Type",
            toit-gen.Literal "application/json",
          ]

    // return api-client_.invoke-api
    //     --path=path
    //     --method=<METHOD>
    //     --query-params=query-params
    //     --header-params=headers
    //     --form-params={:}
    //     --content-type=null
    //     [--body=body]
    invoke-args := [
      toit-gen.Named.external "path" (toit-gen.Ref path-var),
      toit-gen.Named.external "method" (toit-gen.Literal method.to-ascii-upper),
      toit-gen.Named.external "query-params" (toit-gen.Ref query-var),
      toit-gen.Named.external "header-params" (toit-gen.Ref headers-var),
      toit-gen.Named.external "form-params" (toit-gen.Literal {:}),
      toit-gen.Named.external "content-type" (toit-gen.Literal null),
    ]
    if request-body-arg:
      body-expr/toit-gen.Expression := toit-gen.Ref request-body-arg
      if body-needs-json-encode:
        // json.encode body.to-json
        json-imp := ensure-json-import_
        body-expr = toit-gen.Call (json-imp.refer json-encode_)
            --arguments=[toit-gen.Call (toit-gen.Ref request-body-arg) "to-json"]
      invoke-args.add (toit-gen.Named.external "body" body-expr)

    body.ret (toit-gen.Call (toit-gen.Ref api-client-field) "invoke-api" --arguments=invoke-args)
    return body

  append-param-handling_ branch/toit-gen.Sequence
      --param/Parameter
      --vd/toit-gen.VarDefinition
      --path-var/toit-gen.VarDefinition
      --headers-var/toit-gen.VarDefinition
      --query-var/toit-gen.VarDefinition
      --cookie-var/toit-gen.VarDefinition -> none:
    if param.in == Parameter.PATH:
      // path = path.replace --all "{name}" "$value"
      branch.assign path-var
          (toit-gen.Call (toit-gen.Ref path-var) "replace"
              --arguments=[
                toit-gen.Named.external "all" (toit-gen.Literal true),
                toit-gen.Literal "{$param.name}",
                toit-gen.StringInterpolation ["", toit-gen.Ref vd, ""],
              ])
    else if param.in == Parameter.QUERY:
      // query-params.add-all (openapi-runtime.encode-query-param name value [--style=...] [--explode])
      args := [toit-gen.Literal param.name, toit-gen.Ref vd]
      if param.style:
        args.add (toit-gen.Named.external "style" (toit-gen.Literal param.style))
      if param.explode:
        args.add (toit-gen.Named.external "explode" (toit-gen.Literal true))
      branch.invoke (toit-gen.Ref query-var) "add-all"
          --arguments=[toit-gen.Call (runtime_.refer encode-query-param_) --arguments=args]
    else if param.in == Parameter.HEADER:
      // openapi-runtime.encode-header-param headers "name" value
      branch.call (runtime_.refer encode-header-param_)
          --arguments=[
            toit-gen.Ref headers-var,
            toit-gen.Literal param.name,
            toit-gen.Ref vd,
          ]
    else if param.in == Parameter.COOKIE:
      // cookie-params.add "name=$value"
      branch.invoke (toit-gen.Ref cookie-var) "add"
          --arguments=[toit-gen.StringInterpolation ["$param.name=", toit-gen.Ref vd, ""]]

  build-toitdoc_ operation/Operation
      --params/List
      --request-body-arg/toit-gen.VarDefinition?
      --request-body-description/string? -> List?:
    parts := []
    if operation.description: parts.add operation.description
    if operation.deprecated:
      if not parts.is-empty: parts.add "\n\n"
      parts.add "Deprecated."
    params.do: | pair/List |
      param/Parameter := pair[0]
      vd/toit-gen.VarDefinition := pair[1]
      desc := param.description or ""
      if not parts.is-empty: parts.add "\n"
      parts.add "- "
      parts.add (toit-gen.ToitdocNameRef vd)
      parts.add ": $desc"
    if request-body-arg and request-body-description:
      if not parts.is-empty: parts.add "\n"
      parts.add "- "
      parts.add (toit-gen.ToitdocNameRef request-body-arg)
      parts.add ": $request-body-description"
    return parts.is-empty ? null : parts

main args/List:
  positional := []
  i := 0
  while i < args.size:
    arg := args[i]
    if arg == "--template" or arg == "-t":
      // Backwards-compat shim: accept and ignore the flag so existing
      // invocations don't break. The mustache template is gone.
      i += 2
    else:
      positional.add arg
      i++

  if positional.size != 2:
    print "Usage: openapi-gen <openapi.yaml> <output-dir>"
    return

  spec-path := positional[0]
  output-dir := positional[1]

  openapi := build (yaml.decode (file.read-contents spec-path))

  type-resolver := TypeResolver
  api-gen := ApiGenerator --type-resolver=type-resolver
  program := api-gen.gen openapi
  files := program.gen --in-memory

  src-dir := fs.join output-dir "src"
  directory.mkdir --recursive src-dir
  files.do: | rel-path/string content/string |
    out-path := fs.join output-dir rel-path
    out-dir := fs.dirname out-path
    if not file.is-directory out-dir:
      directory.mkdir --recursive out-dir
    file.write-contents --path=out-path content
